# Generated by Django 3.0.5 on 2020-04-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile_link',
        ),
    ]
